version: '2' 

services:
  db:
    container_name: 'haskell_image_gallery_db'
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hig
      POSTGRES_PASSWORD: hig
      POSTGRES_DB: hig

  pastes-api:
    container_name: 'pastes-api'
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend/:/pastes_api/
    depends_on:
        - db
    ports:
      - 3000:3000
    command: /root/.local/bin/pastes-api

  pastes:
    container_name: 'pastes'
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend/:/pastes/
    depends_on:
        - pastes-api
    ports:
      - 8000:8000
